//===--- pass_context.h - Pass Shared Context --------------------*- C++ -*-===//
//
// PawLang Compiler - Pass Context
//
//===----------------------------------------------------------------------===//

#ifndef PAW_PASS_CONTEXT_H
#define PAW_PASS_CONTEXT_H

#include <any>
#include <unordered_map>
#include <string>

namespace pawc {

// Forward declarations
class DiagnosticEngine;
class TypeSystem;
class SymbolTable;
class ModuleLoader;
class Stmt;

/// PassContext - Passbetweenshare/sharedof/thecontext
///
/// provide:
/// - Diagnostic engine access
/// - typessystemvisit
/// - symboltablevisit
/// - Passresultscache
/// - compile/compilationoption
class PassContext {
public:
    PassContext(DiagnosticEngine* diag, 
                TypeSystem* types,
                SymbolTable* symbols)
        : diagnostics_(diag), type_system_(types), symbol_table_(symbols) {}
    
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // Core system access
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    
    DiagnosticEngine* getDiagnostics() const { return diagnostics_; }
    TypeSystem* getTypeSystem() const { return type_system_; }
    SymbolTable* getSymbolTable() const { return symbol_table_; }
    
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // Passresultscache
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    
    /// cachePassanalysisresults
    template<typename T>
    void cacheAnalysisResult(const std::string& pass_name, const T& results) {
        analysis_cache_[pass_name] = results;
    }
    
    /// getcacheof/theanalysisresults
    template<typename T>
    bool getCachedResult(const std::string& pass_name, T& results) {
        auto it = analysis_cache_.find(pass_name);
        if (it != analysis_cache_.end()) {
            try {
                results = std::any_cast<T>(it->second);
                return true;
            } catch (const std::bad_any_cast&) {
                return false;
            }
        }
        return false;
    }
    
    /// Clear cache
    void clearCache() {
        // First clear llvm_module raw pointer, avoid dangling pointer
        analysis_cache_.erase("llvm_module");
        
        // Then clear codegen_context (shared_ptr will correctly destruct)estruct/destruction)
        analysis_cache_.erase("codegen_context");
        
        // Finally clear all other caches
        analysis_cache_.clear();
    }
    
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // compile/compilationoption
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    
    void setOptLevel(int level) { opt_level_ = level; }
    int getOptLevel() const { return opt_level_; }
    
    void setVerbose(bool v) { verbose_ = v; }
    bool isVerbose() const { return verbose_; }
    
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // AST access (used for CodeGen and other passes)
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    
    void setAST(const std::vector<std::unique_ptr<Stmt>>* ast) { ast_ = ast; }
    const std::vector<std::unique_ptr<Stmt>>* getAST() const { return ast_; }
    
private:
    DiagnosticEngine* diagnostics_;
    TypeSystem* type_system_;
    SymbolTable* symbol_table_;
    
    // AST (generated by Parser, passed to subsequent passes)
    const std::vector<std::unique_ptr<Stmt>>* ast_ = nullptr;
    
    // Passanalysisresultscache
    std::unordered_map<std::string, std::any> analysis_cache_;
    
    // compile/compilationoption
    int opt_level_ = 0;
    bool verbose_ = false;
};

} // namespace pawc

#endif // PAW_PASS_CONTEXT_H
